version: '3.7'
services:
  # Databases:

  # MySQL
  ml_sql:
    image: mysql:5.7
    container_name: ml_sql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    # Where our data will be persisted
    networks:
      - ml
    volumes:
      - ml_sql:/var/lib/mysql

  # Mongo
  ml_mongo:
    image: mongo:latest
    container_name: ml_mongo
    restart: always
    networks:
      - ml
    volumes:
      - ml_mongo:/data/db
  # Neo4j
  ml_neo4j:
    container_name: ml_neo4j
    image: neo4j:4.2.3
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - ml
    volumes:
      - ml_neo4j:/data

  # Notebook Environment
  notebooks:
    container_name: notebooks
    build:
       context: .
       dockerfile: ./notebooks/Dockerfile
    volumes:
      - ./notebooks/:/app/notebooks/
      - ./drivers/:/app/drivers/
    ports:
      - 8888:8888
    networks:
      - ml

volumes:
  ml_neo4j:
  ml_mongo:
  ml_sql:
networks:
  ml:
